openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/wesky93/ai-dungeon-api/1.0.0
info:
  description: this is ai dungeon wrapping api for using gpt-3
  version: "0.0.1"
  title: AI Dungeon API
  contact:
    email: wesky93@gmail.com
tags:
  - name: sessions
    description: A session is a kind of room where the context is maintained when talking to gpt-3.
  - name: prompts
    description: |
      This is data to pre-learn the type of response you want in the session. Required when creating a session.
paths:
  /sessions:
    get:
      tags:
        - sessions
      summary: search sessions
      description: search session
      responses:
        '200':
          $ref: '#/components/responses/SessionListResponse'
    post:
      tags:
        - sessions
      summary: search sessions
      description: search session
      requestBody:
        $ref: '#/components/requestBodies/CreateSession'
      responses:
        '200':
          $ref: '#/components/responses/SessionResponse'
  /sessions/{session_id}:
    get:
      tags:
        - sessions
      summary: get session data
      responses:
        '200':
          $ref: '#/components/responses/SessionResponse'
        '404':
          description: session not found
  /sessions/{session_id}/message:
    post:
      tags:
        - sessions
      summary: send message
      requestBody:
        $ref: '#/components/requestBodies/SendMessage'
      responses:
        '200':
          $ref: '#/components/responses/ResultMessage'
        '404':
          description: session not found
  /prompts:
    get:
      tags:
        - prompts
      summary: search prompts
      description: search prompts
      responses:
        '200':
          $ref: '#/components/responses/PromptListResponse'
    post:
      tags:
        - prompts
      summary: add prompt
      description: add prompt
      requestBody:
        $ref: '#/components/requestBodies/CreatePrompt'
      responses:
        '200':
          $ref: '#/components/responses/PromptResponse'
  /prompts/{prompt_id}:
    get:
      tags:
        - prompts
      summary: get prompt data
      responses:
        '200':
          $ref: '#/components/responses/PromptResponse'
        '404':
          description: session not found
    delete:
      summary: delete prompt
      responses:
        '200':
          description: delete prompt

components:
  schemas:
    CreateSession:
      type: object
      required:
        - prompt
        - name
      properties:
       prompt:
         type: string
       name:
         type: string
    CreatePrompt:
      type: object
      required:
        - text
        - name
      properties:
        text:
          type: string
        name:
          type: string
    Message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    PromptItem:
      type: object
      required:
        - name
        - text
        - created_at
      properties:
        name:
          type: string
        text:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    PromptsList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref:  '#/components/schemas/PromptItem'
    History:
      type: object
      properties:
        name:
          type: string
        text:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'

    SessionItem:
      type: object
      required:
        - id
        - name
        - prompt
        - created_at
      properties:
        id:
          type: string
          example: d290f1d701748f0851
        name:
          type: string
        prompt:
          type: string
        history:
          type: array
          items:
            $ref: '#/components/schemas/History'
        created_at:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    SessionList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref:  '#/components/schemas/SessionItem'
  requestBodies:
    CreateSession:
      content:
       application/json:
          schema:
            $ref: '#/components/schemas/CreateSession'
    CreatePrompt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatePrompt'
    SendMessage:
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/Message'
  responses:
    SessionResponse:
      description: >
        session info
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/SessionList'
    SessionListResponse:
      description: >
        list of sessions
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/SessionList'
    PromptResponse:
      description: >
        session info
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/PromptItem'
    PromptListResponse:
      description: >
        list of sessions
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/PromptsList'
    ResultMessage:
      description: >
        return message
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/History'

